### ISSUE TITLE
如何登录微博绑定的账号呢？

### ISSUE THREAD

**Issue by bemvp1** [john-shine/synology-baiduNetdisk-package#11]
登录界面没有选择微博登录的方式，有没别的方式支持呢？例如通过BDUSS或者cookies，或者先登录一个百度的网页之类的，感谢

**Comment by bemvp1** [comment]
baidupcs是通过BDUSS的方式，如果不能增加微博登录的话，这个应该是最方便的方式了

**Comment by john-shine** [comment]
不支持上述的登录方式

**Comment by bemvp1** [comment]
考虑后续支持吗？

**Comment by john-shine** [comment]
此非第三方客户端，没有支持的可能性

**Comment by bemvp1** [comment]
用bduss的方式呢？我看oldiy的baiduups docker在用这个：https://registry.hub.docker.com/u/oldiy/baidupcs/
因为我现在账号完全没法用了，感谢

**Comment by john-shine** [comment]
实现不了的哦
