### ISSUE TITLE
重启后一直在登录页面

### ISSUE THREAD

**Issue by bemvp1** [john-shine/synology-baiduNetdisk-package#12]
正在下载着时群晖重启了，重启后再进入时，一直在登录界面等待状态，就是那几个点在不断变化，没有登录框也没进入下载界面

**Comment by john-shine** [comment]
Duplicate of #8

> 客户端停留在加载界面的进度条中，一直无法进入主界面，也不出现登录界面，怎么办？
> 
> 在BDdownload文件夹下创建一个.reset文件夹。然后，重启johnshine/baidunetdisk-crossover-vnc:latest对应的docker容器即可。
> 
> 这个应该是客户端本身的登录问题，清除后，需要重新登录客户端。
>

**Comment by john-shine** [comment]
Duplicate of #8

> 客户端停留在加载界面的进度条中，一直无法进入主界面，也不出现登录界面，怎么办？
> 
> 在BDdownload文件夹下创建一个.reset文件夹。然后，重启johnshine/baidunetdisk-crossover-vnc:latest对应的docker容器即可。
> 
> 这个应该是客户端本身的登录问题，清除后，需要重新登录客户端。
>

**Comment by bemvp1** [comment]
试了还是不行，还是四个点
先新建文件夹，再关闭，再开启，不行；
先关闭，再新建文件夹，再开启，也不行。
