### ISSUE TITLE
手动安装时报错命令运行失败

### ISSUE THREAD

**Issue by MyFaith** [john-shine/synology-baiduNetdisk-package#15]
![image](https://user-images.githubusercontent.com/8826441/82782653-6af25600-9e8f-11ea-972f-c1e81d54e426.png)

**Comment by john-shine** [comment]
是不是没有预先下载docker镜像？最好能发送一下安装日志

**Comment by MyFaith** [comment]
![image](https://user-images.githubusercontent.com/8826441/82982709-4e862300-a021-11ea-9313-6a45add25fd4.png)

日志从哪里看？
