### ISSUE TITLE
内存泄漏+无法运行？

### ISSUE THREAD

**Issue by sun47451685** [john-shine/synology-baiduNetdisk-package#16]
百度云linux版已经升到3.0.1了，不知楼主啥时候会跟进。
另外，这可能是这个版本的问题：没办法控制同时下载数量的多少。
例如，我列了30个任务在队列。
百度云有时候是一个一个下载，有时候会同时下载2/5个任务。

还有很多时候，会出现，一个任务下载到一半变成等待中，然后软件继续下载其他任务。。

多个任务的时候，内存就会变得很不可控制，一个任务占用内存800mb左右，多个任务内存的占用会超过4g，然后整个群晖就会变得卡顿死机（我配了8g内存）

不清楚百度云的任务缓存是怎么处理的。

**Comment by sun47451685** [comment]
今天更新了docker。
百度云貌似就卡在进入的四个小点上，无法启动了。

**Comment by john-shine** [comment]
@sun47451685 内存泄漏的问题我这里无能为力，只能是百度官方去更新
第2个问题在README中有提到：

> 客户端停留在加载界面的进度条中，一直无法进入主界面，也不出现登录界面，怎么办？
> 
> 在BDdownload文件夹下创建一个.reset文件夹。然后，重启johnshine/baidunetdisk-crossover-vnc:latest对应的docker容器即可。
> 
> 这个应该是客户端本身的登录问题，清除后，需要重新登录客户端。
