### ISSUE TITLE
无法加载baidu登录画面

### ISSUE THREAD

**Issue by cheyj55** [john-shine/synology-baiduNetdisk-package#20]
无法加载baidu登录画面

**Comment by john-shine** [comment]
能发下docker容器内的运行日志吗，路径在/home/baidu/.vnc/xxxxxx.log

**Comment by cheyj55** [comment]
帮忙看看吧，谢谢
[e27f74b529f5-1.log](https://github.com/john-shine/synology-baiduNetdisk-package/files/5078160/e27f74b529f5-1.log)

**Comment by shit6** [comment]
请问解决了吗？一样的问题

**Comment by cheyj55** [comment]
还没有

**Comment by planiets** [comment]
请问是打开之后一片灰色的界面什么都没有吗？我卸载重装了再打开还是这样

**Comment by rekcah1986** [comment]
我的也是灰屏

Press Ctrl-C .0.1: Path: '/websockify'                                                         
172.17.0.1 - - [22/Aug/2020 04:03:58] connecting to: 127.0.0.1:5901                            
                                                                                               
Sat Aug 22 04:03:58 2020                                                                       
to exit                                                                                        
                                                                                               
                                                                                               
WebSocket server settings:                                                                     
  - Listen on :6080                                                                            
  - Web server. Web root: /opt/noVNC-1.1.0                                                     
  - No SSL/TLS support (no cert file)                                                          
  - proxying from :6080 to 127.0.0.1:5901                                                      
/home/baidu/.vnc/xstartup: line 25:    82 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   145 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   197 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   250 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               


Press Ctrl-C .0.1: Path: '/websockify'                                                         
172.17.0.1 - - [22/Aug/2020 04:03:58] connecting to: 127.0.0.1:5901                            
                                                                                               
Sat Aug 22 04:03:58 2020                                                                       
to exit                                                                                        
                                                                                               
                                                                                               
WebSocket server settings:                                                                     
  - Listen on :6080                                                                            
  - Web server. Web root: /opt/noVNC-1.1.0                                                     
  - No SSL/TLS support (no cert file)                                                          
  - proxying from :6080 to 127.0.0.1:5901                                                      
/home/baidu/.vnc/xstartup: line 25:    82 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   145 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   197 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1                                               
/home/baidu/.vnc/xstartup: line 25:   250 Aborted                 /opt/baidunetdisk/baidunetdis
k --no-sandbox >> /var/log/baidunetdisk.log 2>&1

**Comment by xing00you** [comment]
解决没有？我也这样。

**Comment by john-shine** [comment]
<img width="887" alt="屏幕快照 2020-08-27 下午11 24 16" src="https://user-images.githubusercontent.com/6376135/91462225-8882f180-e8bc-11ea-91ed-3ad51765b77d.png">
这里正常运行，不能运行的朋友再docker中运行如下命令，把结果贴出来一下：
dmesg|grep -i baidunetdisk

**Comment by cheyj55** [comment]
bash-4.2$ 
bash-4.2$ 
bash-4.2$ dmesg|grep -i baidunetdisk
[37635.624261] init: pkgctl-BaiduNetdisk post-stop process (8236) terminated with status 1
bash-4.2$

**Comment by houtong1993** [comment]
![QQ浏览器截图20200828115345](https://user-images.githubusercontent.com/70359898/91519446-3a560880-e925-11ea-8bf9-5097a91d7a92.png)
请大佬帮忙看看

**Comment by john-shine** [comment]
主要是这版本的百度云客户端做的太差，不同的系统环境出现非常多的不兼容的情况，导致启动失败

**Comment by planiets** [comment]
之前是可以的，但是一登陆进去就提示请升级到新版本，然后就重装了一下才出现这样的问题了

**Comment by Zther0** [comment]
![image](https://user-images.githubusercontent.com/19760820/91683302-d16dcb00-eb86-11ea-901b-ddf456b70b03.png)

**Comment by Zther0** [comment]
无法显示

**Comment by john-shine** [comment]
@所有人 群晖DSM6目前使用的linux内核是3.10版本，docker运行原理觉得它完全共享主机内核，但百度新的linux客户端又只能在3.17以上内核下运行，以下内核因为动态链接库不兼容，导致很多问题，目前没有解决办法。只能说百度出的这个客户端太烂了，目前只能回退到旧版本的docker镜像。
