### ISSUE TITLE
一直提示“账户已过期”与“检测到新版本”

### ISSUE THREAD

**Issue by Cyberxxt** [john-shine/synology-baiduNetdisk-package#21]
![{60BC56F0-82AD-486C-BF19-C0780A6E3C6F} png](https://user-images.githubusercontent.com/40683077/90236623-96189000-de55-11ea-9c3a-b2a8644ee9d7.jpg)

如图，登陆后一直提示账户已过期，随后自动登出。已尝试新建.reset文件夹重置，问题依旧

每次打开不管有无登录都会提示检测到新版本，点击后没有任何反应

**Comment by john-shine** [comment]
更新到最新版，需要重新套件。或者自己重新拉取映像，重新运行成容器
