### ISSUE TITLE
找不到下载的文件

### ISSUE THREAD

**Issue by sailei00** [john-shine/synology-baiduNetdisk-package#22]

**Comment by lovedeeply** [comment]
me too.
bug..

**Comment by john-shine** [comment]
<img width="719" alt="屏幕快照 2020-08-27 下午11 35 57" src="https://user-images.githubusercontent.com/6376135/91463576-25925a00-e8be-11ea-9cfe-e502748c7697.png">

设置，选择下载目录到/home/baidu/baidunetdiskdownload

默认下载到/home/baidu/，是找不到下载文件的

**Comment by anonymous216041** [comment]
问题是选择了，不知道在哪里确认选择
