### ISSUE TITLE
docker安装后，连接黑屏

### ISSUE THREAD

**Issue by zlhdd108** [john-shine/synology-baiduNetdisk-package#26]
docker安装后，连接黑屏
用vnc连接直接报错，无法连接；直接用6080的web连接，就是黑屏，不过鼠标并不是叉叉，看不到东西

**Comment by limanman77** [comment]
同黑屏😭

<img width="1230" alt="截屏2020-09-09 下午4 36 57" src="https://user-images.githubusercontent.com/26197836/92575454-eb13be80-f2ba-11ea-88f0-eb2aa584105a.png">

**Comment by limanman77** [comment]
<img width="2122" alt="截屏2020-09-09 下午5 00 26" src="https://user-images.githubusercontent.com/26197836/92578141-0fbd6580-f2be-11ea-8b38-d7bd5ef7c894.png">

**Comment by john-shine** [comment]
已更新，请安装新版本spk包
