### ISSUE TITLE
安装没有问题，登录账号显示

### ISSUE THREAD

**Issue by xiehaoing** [john-shine/synology-baiduNetdisk-package#27]
登录显示账号已经过期，然后就自动退出，求解

**Comment by john-shine** [comment]
是自行编译的，还是在release页面下载的。自行编译的，需要再编译下，部分代码没有提交

**Comment by xiehaoing** [comment]
> 是自行编译的，还是在release页面下载的。自行编译的，需要再编译下，部分代码没有提交

我是在群晖里下载的最新的镜像文件，然后安装最新的spk文件，直接运行，登录显示账号已经过期，然后就自动退出，转化

**Comment by kmyqchy** [comment]
我也是……

**Comment by freemangl** [comment]
我今天刚刚安装的也是这个提示。无法正常使用。

**Comment by john-shine** [comment]
docker容器内中ping下 update.pan.baidu.com，即如下命令：
update.pan.baidu.com
看看返回的是什么

**Comment by danielhuoo** [comment]
> docker容器内中ping下 update.pan.baidu.com，即如下命令：
> update.pan.baidu.com
> 看看返回的是什么

```bash
baidu@022c7d547ca7:~$ ping update.pan.baidu.com                                                                                                 
PING update.pan.baidu.com (127.0.0.1) 56(84) bytes of data.                                                                                     
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.062 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.060 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.059 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.048 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.060 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.060 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=7 ttl=64 time=0.059 ms                                                                            
64 bytes from localhost (127.0.0.1): icmp_seq=8 ttl=64 time=0.057 ms                                                                            
^C                                                                                                                                              
--- update.pan.baidu.com ping statistics ---                                                                                                    
8 packets transmitted, 8 received, 0% packet loss, time 7000ms                                                                                  
rtt min/avg/max/mdev = 0.048/0.058/0.062/0.005 ms   

```

**Comment by aszyue** [comment]
我刚下载安装也是这个提示，过期

**Comment by astoc-fan** [comment]
+1

**Comment by RWDai** [comment]
> docker容器内中ping下 update.pan.baidu.com，即如下命令：
> update.pan.baidu.com
> 看看返回的是什么
`PING update.pan.baidu.com (180.149.145.242): 56 data bytes
64 bytes from 180.149.145.242: seq=0 ttl=53 time=33.567 ms
64 bytes from 180.149.145.242: seq=1 ttl=53 time=32.384 ms
64 bytes from 180.149.145.242: seq=2 ttl=53 time=32.311 ms
64 bytes from 180.149.145.242: seq=3 ttl=53 time=32.382 ms
64 bytes from 180.149.145.242: seq=4 ttl=53 time=32.567 ms
64 bytes from 180.149.145.242: seq=5 ttl=53 time=32.661 ms
64 bytes from 180.149.145.242: seq=6 ttl=53 time=32.591 ms
64 bytes from 180.149.145.242: seq=7 ttl=53 time=32.224 ms
64 bytes from 180.149.145.242: seq=8 ttl=53 time=32.178 ms
64 bytes from 180.149.145.242: seq=9 ttl=53 time=32.449 ms
64 bytes from 180.149.145.242: seq=10 ttl=53 time=32.503 ms
64 bytes from 180.149.145.242: seq=11 ttl=53 time=32.266 ms
64 bytes from 180.149.145.242: seq=12 ttl=53 time=32.402 ms
^C
--- update.pan.baidu.com ping statistics ---
13 packets transmitted, 13 packets received, 0% packet loss
round-trip min/avg/max = 32.178/32.498/33.567 ms`
我也遇到这个情况

**Comment by aszyue** [comment]
PING update.pan.baidu.com (127.0.0.1) 56(84) bytes of data.                                              
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.037 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=2 ttl=64 time=0.040 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=3 ttl=64 time=0.041 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=4 ttl=64 time=0.041 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=5 ttl=64 time=0.038 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=6 ttl=64 time=0.042 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=7 ttl=64 time=0.042 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=8 ttl=64 time=0.046 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=9 ttl=64 time=0.040 ms                                     
64 bytes from localhost (127.0.0.1): icmp_seq=10 ttl=64 time=0.040 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=11 ttl=64 time=0.039 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=12 ttl=64 time=0.042 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=13 ttl=64 time=0.039 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=14 ttl=64 time=0.041 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=15 ttl=64 time=0.039 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=16 ttl=64 time=0.040 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=17 ttl=64 time=0.038 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=18 ttl=64 time=0.042 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=19 ttl=64 time=0.040 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=20 ttl=64 time=0.041 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=21 ttl=64 time=0.041 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=22 ttl=64 time=0.039 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=23 ttl=64 time=0.039 ms                                    
64 bytes from localhost (127.0.0.1): icmp_seq=24 ttl=64 time=0.041 ms

**Comment by FBI998** [comment]
![Uploading 1.png…]()

**Comment by amelaxie** [comment]
我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker 镜像
dpkg -i baidunetdisk_3.4.1_amd64.deb

**Comment by palmlinss** [comment]
提示账号已过期，不能登录，求解。。。

**Comment by xiehaoing** [comment]
> 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> dpkg -i baidunetdisk_3.4.1_amd64.deb

请指教 如何升级docker 系统里百度云客户端

**Comment by palmlinss** [comment]
> > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > dpkg -i baidunetdisk_3.4.1_amd64.deb
> 
> 请指教 如何升级docker 系统里百度云客户端

下载baidunetdisk_3.4.1_amd64.deb
在终端机里 执行 sudo  dpkg -i baidunetdisk_3.4.1_amd64.deb
但我试了下，最后连登录面页都不见了。

**Comment by amelaxie** [comment]
> > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > 
> > 
> > 请指教 如何升级docker 系统里百度云客户端
> 
> 下载baidunetdisk_3.4.1_amd64.deb
> 在终端机里 执行 sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> 但我试了下，最后连登录面页都不见了。

我前面一直试了失败，然后把docker、 baidunetdisk都卸载，重新安装了一遍，然后把 baidunetdisk升级，还有就是把/etc/hosts
 update.pan.baidu.com那一行也注释掉了，你重启试过吗

**Comment by palmlinss** [comment]
> > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 
> > > 
> > > 请指教 如何升级docker 系统里百度云客户端
> > 
> > 
> > 下载baidunetdisk_3.4.1_amd64.deb
> > 在终端机里 执行 sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> > 但我试了下，最后连登录面页都不见了。
> 
> 我前面一直试了失败，然后把docker、 baidunetdisk都卸载，重新安装了一遍，然后把 baidunetdisk升级，还有就是把/etc/hosts
> update.pan.baidu.com那一行也注释掉了，你重启试过吗

重启了，没用，现在连登录面页都不出现了。

**Comment by xiehaoing** [comment]
> > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker 
> > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 
> > > 
> > > 请指教如何升级docker系统里百度云客户端
> > 
> > 
> > 下载baidunetdisk_3.4.1_amd64.deb 
> > 在终端机里执行sudo dpkg -i baidunetdisk_3.4.1_amd64.deb 
> > 但我试了下，最后连登录面页都不见了。
> 
> 我前面一直试了失败，然后把docker，baidunetdisk都卸载，重新安装了一遍，然后把baidunetdisk升级，还有就是把/ etc / hosts
> update.pan.baidu.com那一行也注释掉了，你重启试过吗

怎么把升级包上传到docker容器里去  输入命令 提示 dpkg: error: cannot access archive 'baidunetdisk_3.4.1_amd64.deb': No such file or directory

**Comment by amelaxie** [comment]
> > > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > > 
> > > > 
> > > > 请指教如何升级docker系统里百度云客户端
> > > 
> > > 
> > > 下载baidunetdisk_3.4.1_amd64.deb
> > > 在终端机里执行sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 但我试了下，最后连登录面页都不见了。
> > 
> > 
> > 我前面一直试了失败，然后把docker，baidunetdisk都卸载，重新安装了一遍，然后把baidunetdisk升级，还有就是把/ etc / hosts
> > update.pan.baidu.com那一行也注释掉了，你重启试过吗
> 
> 怎么把升级包上传到docker容器里去 输入命令 提示 dpkg: error: cannot access archive 'baidunetdisk_3.4.1_amd64.deb': No such file or directory

最简单的就是通过nas的下载目录传过去，baidudownload.那个目录，容器里面是会挂载这个目录的

**Comment by john-shine** [comment]
ping update.pan.baidu.com 如果结果显示ip是127.0.0.1，说明hosts生效了。添加这个host目的就是为了屏蔽百度网盘检测更新，进而提示“账号已经过期”，并自动退出登录。但尚不清楚为什么在我这里有效果，但是部分群众的环境下没效果。

尝试升级到客户端到3.4.1版本也是可以的，不过在部分nas下，无法兼容，导致客户端无法启动，只有黑屏，所以为了兼容性，把客户端的版本都固定到了3.0.1.2版本，如果你的nas有幸可以兼容，升级到最新版本当然最好

**Comment by w4lle** [comment]
> ping update.pan.baidu.com 如果结果显示ip是127.0.0.1，说明hosts生效了。添加这个host目的就是为了屏蔽百度网盘检测更新，进而提示“账号已经过期”，并自动退出登录。但尚不清楚为什么在我这里有效果，但是部分群众的环境下没效果。
> 
> 尝试升级到客户端到3.4.1版本也是可以的，不过在部分nas下，无法兼容，导致客户端无法启动，只有黑屏，所以为了兼容性，把客户端的版本都固定到了3.0.1.2版本，如果你的nas有幸可以兼容，升级到最新版本当然最好

碰到同样的问题，如何解决呢？请教客户端版本如何升级？

**Comment by xiaominglei001** [comment]
> > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 
> > > 
> > > 请指教 如何升级docker 系统里百度云客户端
> > 
> > 
> > 下载baidunetdisk_3.4.1_amd64.deb
> > 在终端机里 执行 sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> > 但我试了下，最后连登录面页都不见了。
> 
> 我前面一直试了失败，然后把docker、 baidunetdisk都卸载，重新安装了一遍，然后把 baidunetdisk升级，还有就是把/etc/hosts
> update.pan.baidu.com那一行也注释掉了，你重启试过吗

/etc/hosts
update.pan.baidu.com  这一行在哪里修改？哪个文件怎么找到的，不懂啊，目前我更新了deb，进去登录成功后一片灰色空白。。

**Comment by xiaominglei001** [comment]
> > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 
> > > 
> > > 请指教 如何升级docker 系统里百度云客户端
> > 
> > 
> > 下载baidunetdisk_3.4.1_amd64.deb
> > 在终端机里 执行 sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> > 但我试了下，最后连登录面页都不见了。
> 
> 我前面一直试了失败，然后把docker、 baidunetdisk都卸载，重新安装了一遍，然后把 baidunetdisk升级，还有就是把/etc/hosts
> update.pan.baidu.com那一行也注释掉了，你重启试过吗

我升级到3.4.1了，否则一直重复登陆退出，但是升级后，打开登陆之后，一片灰色背景，没法用，你这说注释掉“update.pan.baidu.com”，我用putty连到群晖上，发现/etc/hosts里没有这句话啊，难道找错地方了？

**Comment by xiaominglei001** [comment]
> > > > > 我从百度下了个3.4.1的deb包，升级一下就可以用了，有空可以自己做个docker
> > > > > dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > > 
> > > > 
> > > > 请指教 如何升级docker 系统里百度云客户端
> > > 
> > > 
> > > 下载baidunetdisk_3.4.1_amd64.deb
> > > 在终端机里 执行 sudo dpkg -i baidunetdisk_3.4.1_amd64.deb
> > > 但我试了下，最后连登录面页都不见了。
> > 
> > 
> > 我前面一直试了失败，然后把docker、 baidunetdisk都卸载，重新安装了一遍，然后把 baidunetdisk升级，还有就是把/etc/hosts
> > update.pan.baidu.com那一行也注释掉了，你重启试过吗
> 
> 我升级到3.4.1了，否则一直重复登陆退出，但是升级后，打开登陆之后，一片灰色背景，没法用，你这说注释掉“update.pan.baidu.com”，我用putty连到群晖上，发现/etc/hosts里没有这句话啊，难道找错地方了？

解决了，但是用的另一个映像解决的，谁有需要可以参考下
映像地址：
https://registry.hub.docker.com/r/johngong/baidunetdisk/
注意事项：（DSM6.1.7用3.0.1版本，DSM6.2.2以上再用最新版本）
https://github.com/gshang2017/docker/issues/43

**Comment by john-shine** [comment]
升级DSM，并重新安装此套件，原因参见README
