### ISSUE TITLE
1.07版本又出现账号已过期了

### ISSUE THREAD

**Issue by Cyberxxt** [john-shine/synology-baiduNetdisk-package#32]
死活登不上，一直提示账号已过期
ping update.pan.baidu.com返回结果如下

64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=33 ttl=53 time=46.0 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=34 ttl=53 time=46.1 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=35 ttl=53 time=46.2 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=36 ttl=53 time=45.6 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=37 ttl=53 time=45.2 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=38 ttl=53 time=45.9 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=39 ttl=53 time=45.9 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=40 ttl=53 time=45.7 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=41 ttl=53 time=46.1 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=42 ttl=53 time=46.0 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=43 ttl=53 time=46.3 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=44 ttl=53 time=45.2 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=45 ttl=53 time=46.0 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=46 ttl=53 time=45.9 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=47 ttl=53 time=46.0 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=48 ttl=53 time=46.1 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=49 ttl=53 time=46.0 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=50 ttl=53 time=45.3 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=51 ttl=53 time=45.3 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=52 ttl=53 time=45.4 ms                
64 bytes from 180.149.145.242 (180.149.145.242): icmp_seq=53 ttl=53 time=45.4 ms                
^C                                                                                              
--- update.pan.n.shifen.com ping statistics ---                                                 
53 packets transmitted, 53 received, 0% packet loss, time 52061ms                               
rtt min/avg/max/mdev = 45.169/45.901/46.536/0.449 ms

**Comment by leexin1984** [comment]
同样问题，登录不了，向大佬求救！

**Comment by john-shine** [comment]
升级DSM，并重新安装套件，参见README
