### ISSUE TITLE
最新百度云客户端docker无法使用了

### ISSUE THREAD

**Issue by junny-yuan** [john-shine/synology-baiduNetdisk-package#34]
安装好docker容器后打开无法出现百度云登陆界面了，一片灰色。
DSM版本是6.2.3
![image](https://user-images.githubusercontent.com/75459172/101110122-4b44a300-3613-11eb-82f2-53709a33825b.png)

**Comment by john-shine** [comment]
百度客户端未启动，运行命令：uname -a，看下内核的版本

**Comment by joke2003** [comment]
我也是上面那个样子的，一片灰茫茫，uname -a得到的结果是下面这样：
Linux NAS 3.10.105 #25426 SMP Mon Dec 14 18:45:24 CST 2020 x86_64 GNU/Linux synology_braswell_916+

**Comment by john-shine** [comment]
必须是Linux NAS 4.x.x的才支持新版客户端，你需要升级您群晖的dsm版本

**Comment by junny-yuan** [comment]
我现在DSM版本是6.2.3，请问是需要升级到7.0才可以吗？
