### ISSUE TITLE
在群晖上无法下载baiduNetdisk的Docker镜像文件

### ISSUE THREAD

**Issue by hrbagang** [john-shine/synology-baiduNetdisk-package#37]
可能是由于墙的原因，我这边，在群晖上下载baiduNetdisk的Docker镜像文件，屡次都失败了。
在网上找群晖Docker的加速服务器，也都无效，这些加速服务器上面没有baiduNetdisk的Docker镜像文件。
谁有下载好的baiduNetdisk的Docker镜像文件，还望能共享下。
或者有可以下载baiduNetdisk的Docker镜像文件的加速服务器地址，也可以。
先谢谢啦。

**Comment by john-shine** [comment]
镜像已上传，可上传到群晖中，并在ssh终端下运行：
docker load < baidunetdisk-crossover-vnc\:latest.tar
