### ISSUE TITLE
frp 穿透6900端口无法访问百度云。

### ISSUE THREAD

**Issue by LunaticTian** [john-shine/synology-baiduNetdisk-package#4]
直接用docker搭建映射相关端口可进行VNC连接(frp穿透亦可)，但若用该项目搭建出的6900端口http内网可正常访问操作，但是frp穿透可以进入网页却无法出现百度云linux客户端界面，vnc也无法连接。

**Comment by john-shine** [comment]
NoVNC走得是websocket，frp配置成tcp协议，或者 nginx端做反向代理，转发websocket，参考：https://www.xncoding.com/2018/03/12/fullstack/nginx-websocket.html
