### ISSUE TITLE
没有设置对下载路径

### ISSUE THREAD

**Issue by lulufxl** [john-shine/synology-baiduNetdisk-package#41]
下载的时候没有设置成/home/baidu/baidunetdiskdownload，直接下载了，现在下载好后抓瞎了，哪里去找到已经下载的文件？
路径正确后已测试可以下载到文件夹。只是原来那个直接下载的文件是否能找到，谢谢回复。

**Comment by john-shine** [comment]
再下载一遍，或者在docker - 容器 - 详情 - 终端下，运行mv命令，将下载好的文件移动到/home/baidu/baidunetdiskdownload文件夹下面
https://wangchujiang.com/linux-command/c/mv.html

**Comment by percygao** [comment]
> 再下载一遍，或者在docker - 容器 - 详情 - 终端下，运行mv命令，将下载好的文件移动到/home/baidu/baidunetdiskdownload文件夹下面
> https://wangchujiang.com/linux-command/c/mv.html

小白自学了很久，百度了mv命令，但是不知道下载在哪个位置，无从移动，请大佬指教。在/home/baidu/目录下有下载的文件夹，但是终端机里ls命令列出来就没有，cd文件夹名字也没有
