### ISSUE TITLE
DSM 6.2.3 百度客户端一直在启动页面

### ISSUE THREAD

**Issue by whjiang** [john-shine/synology-baiduNetdisk-package#42]
DSM 6.2.3最新版本，启动docker后，客户端一直在百度网盘启动页面，无法进入主界面。BDDownload下加`.reset`目录的方法也试了，没有效果。

docker镜像是latest，spk是1.0.7

**Comment by john-shine** [comment]
网络正常吗

**Comment by whjiang** [comment]
很正常。同网络的百度网盘电脑版可正常访问百度网盘。

**Comment by windknight223** [comment]
我也是同样的问题，今天刚安装的，配置和楼主相同，谢谢。

**Comment by jeffreyouni** [comment]
网络正常的，但是打开后显示网络错误，1.0.7的spk
1.0.6的加载错误，-105_1_ERR_NAME_NOT_RESOLVED
试过.reset

**Comment by john-shine** [comment]
ERR_NAME_NOT_RESOLVED说明是网络DNS问题，无法解析到百度云服务器的IP地址，请检查网络配置
