### ISSUE TITLE
看的安装教程没说要改默认下载路径，结果下了二十多G文件，有没有办法找到在哪？

### ISSUE THREAD

**Issue by percygao** [john-shine/synology-baiduNetdisk-package#44]

**Comment by YanYanLun** [comment]
BDDownload

**Comment by coderFuYu** [comment]
同样未改默认地址，来分享一下解决方法
- 使用ssh连接群晖
- 使用find命令找到文件目录
```shell
 find / -type d -iname "baidunetdiskdownload"
```
- 找到一条记录
![image](https://user-images.githubusercontent.com/42110911/151498368-33799e1c-509d-4116-b244-c701e1c0e897.png)
- 进入到前面的文件夹，发现就是我们下载东西的文件夹
![image](https://user-images.githubusercontent.com/42110911/151498487-4e7e8037-53d5-43e0-a901-0442a6c96db4.png)
- 删除或者移动这个文件夹，这里我选择了删除
![image](https://user-images.githubusercontent.com/42110911/151498585-7f90641c-ff7b-4828-a15b-6ea2fd832eae.png)
