### ISSUE TITLE
下载的文件在哪，怎么自定义下载的位置

### ISSUE THREAD

**Issue by 4ppp44** [john-shine/synology-baiduNetdisk-package#46]
rt

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by 4ppp44** [comment]
> rt
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

**Comment by YanYanLun** [comment]
BDDownload
