### ISSUE TITLE
 打开之后只有显示灰色屏幕和顶部菜单栏，没有百度云的窗体

### ISSUE THREAD

**Issue by yunxiuGona** [john-shine/synology-baiduNetdisk-package#47]
![微信图片_20210805102540](https://user-images.githubusercontent.com/4360198/128281217-29211a8f-919b-463a-8593-725e9dfb5b32.png)
![微信图片_20210805102612](https://user-images.githubusercontent.com/4360198/128281226-53186b1e-3e01-4ffa-a507-8a6685e7a639.png)

Docker日志也没有特别的错误LOG

**Comment by yunxiuGona** [comment]
Docker设置
![微信图片_20210805103451](https://user-images.githubusercontent.com/4360198/128281993-3b097d1f-031d-49ef-bbad-c0b7ce0be51f.png)
![微信图片_20210805103420](https://user-images.githubusercontent.com/4360198/128282001-d95ae336-7630-4530-a5e2-b247db548e82.png)

**Comment by YanYanLun** [comment]
inspiring_torvalds服务没启动

**Comment by shinfly** [comment]
我也是窗口内显显示灰色屏幕跟楼主的一样连日志的内容者有一样.楼主问题解决了吗?

**Comment by shinfly** [comment]
> 
> 
> inspiring_torvalds服务没启动

什么启动?

**Comment by YanYanLun** [comment]
docker里面有一个inspiring_torvalds服务没启动

**Comment by shinfly** [comment]
> 
> 
> docker里面有一个inspiring_torvalds服务没启动

能具体一些,.刚开始用docker不清楚inspiring_torvalds在哪里启动

**Comment by YanYanLun** [comment]
![image](https://user-images.githubusercontent.com/17606580/132155116-454d51d1-5fa6-43bc-a8ce-6a1aaaf5e89d.png)
记得启动这两个服务

**Comment by YanYanLun** [comment]
https://github.com/john-shine/synology-baiduNetdisk-package/issues/47#issuecomment-913124115，看上面我的回复

**Comment by dragon00kk** [comment]
![image](https://user-images.githubusercontent.com/31162175/135588481-84c47165-b949-4e26-915f-66e19cada3ac.png)
你好，我安裝了，但是docker里没有inspiring_torvalds怎么办呢？我的是DS3617xs

**Comment by shinfly** [comment]
我的也没有，到现在还没运行成功。你找到运行成功方法告诉我一声，谢谢发自我的华为手机-------- 原始邮件 --------发件人： dragon00kk ***@***.***>日期： 2021年10月1日周五 下午4:22收件人： john-shine/synology-baiduNetdisk-package ***@***.***>抄送： shinfly ***@***.***>, Comment ***@***.***>主    题： Re: [john-shine/synology-baiduNetdisk-package]  打开之后只有显示灰色屏幕和顶部菜单栏，没有百度云的窗体 (#47)



你好，我安裝了，但是docker里没有inspiring_torvalds怎么办呢？我的是DS3617xs

**Comment by jiangpengwz** [comment]
@YanYanLun @john-shine 群晖docker注册表里，没有 inspiring torvalds 这个东西了。。。咋回事

**Comment by qwsxmkoi** [comment]
今天我安装也遇到了这个问题，后来我尝试直接安装docker里面的套件而不是使用.spk文件让他自动安装docker，然后就正常了
我发现使用.spk安装的话会比docker直接安装套件少一个端口没有设置，这可能就是为何虚拟机里百度云没有启动的原因
如图为docker直接安装，多了一个5901的端口
![image](https://user-images.githubusercontent.com/18901221/150003796-b1420dc3-0e0e-47c9-b323-a9af33720184.png)

**Comment by yunxiuGona** [comment]
更新一下，前天重装了一下Docker镜像，发现现在可以用了，应该是作者更新了镜像，现在只有clever_wright镜像，现在能够完美运行了，不错，感谢
![image](https://user-images.githubusercontent.com/4360198/155641968-5509ce3a-8fee-42ea-90e7-5dd640ba7d35.png)
![image](https://user-images.githubusercontent.com/4360198/155641982-60fc5fa8-9c8d-4e8c-a205-0f2c8fb8a566.png)

**Comment by yunxiuGona** [comment]
![image](https://user-images.githubusercontent.com/4360198/155642037-9e0e1e6a-76e2-4d0f-936f-e9feeb6269ff.png)
