### ISSUE TITLE
只有灰色的桌面

### ISSUE THREAD

**Issue by 0xAmad3us** [john-shine/synology-baiduNetdisk-package#52]

**Comment by 0xAmad3us** [comment]
![image](https://user-images.githubusercontent.com/96514177/147042754-00eae313-a1bb-4086-a5fd-d4be47d31ae2.png)
![image](https://user-images.githubusercontent.com/96514177/147042814-8748ca7e-be9e-46e2-84d8-442ee1a70eeb.png)

**Comment by john-shine** [comment]
百度云版本问题，已更新README说明
