### ISSUE TITLE
打开后只有灰色的页面的解决办法

### ISSUE THREAD

**Issue by qwsxmkoi** [john-shine/synology-baiduNetdisk-package#53]
今天我安装也遇到了这个问题，后来我尝试直接安装docker里面的套件而不是使用.spk文件让他自动安装docker套件，然后就正常了
我发现使用.spk安装的话会比docker直接安装套件少一个端口没有设置，这可能就是为何虚拟机里百度云没有启动的原因
如图为docker直接安装，多了一个5901的端口
![image](https://user-images.githubusercontent.com/18901221/150003921-1c77b371-77de-4ae6-9393-574326c8cebb.png)
建议都试试直接使用docker安装然后手动输入ip:6900链接，不要使用这里下的.spk文件

**Comment by john-shine** [comment]
百度云版本问题，已更新README说明
