### ISSUE TITLE
如何增加vnc密码？或者考虑内置密码访问

### ISSUE THREAD

**Issue by avsba001** [john-shine/synology-baiduNetdisk-package#6]
用Https反代到外网，有端口号直接可以访问，有考虑加吗，或者我们能自己解决

**Comment by john-shine** [comment]
可以考虑在反向代理层面添加HTTP basic auth，例如nginx：https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

后续考虑增加安装时设置密码的选项

**Comment by john-shine** [comment]
@avsba001 新版本已更新，问题可参照README.md
