### ISSUE TITLE
群辉重启后网盘卡logo

### ISSUE THREAD

**Issue by avsba001** [john-shine/synology-baiduNetdisk-package#8]
![QQ截图20200419210432](https://user-images.githubusercontent.com/29015932/79688532-77c4ce00-8281-11ea-8deb-e1c72578c20e.png)

重启后套件和docker内镜像正常启动，但一直卡logo
尝试过手动重启套件和镜像问题依旧

**Comment by john-shine** [comment]
阅读readme.md
