### ISSUE TITLE
提示登录失败，请重新登录，重试了好几次依然无法登录

### ISSUE THREAD

**Issue by xieshang** [john-shine/synology-baiduNetdisk-package#9]
提示登录失败，请重新登录，重试了好几次依然无法登录。

**Comment by john-shine** [comment]
有没有截图

**Comment by xieshang** [comment]
> 有没有截图

不好意思，已经登录成功了。

尝试登录了3次：群辉登录，提示“登录失败”；---> 浏览器退出重新登录，提示验证手机号；---> 群辉再次登录，提示“登录失败”；--->隔2个多小时后再试，登录成功。
